plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'org.jetbrains.kotlin.plugin.serialization'
}

group = 'com.naijaayo'
version = '1.0-SNAPSHOT'

dependencies {
    implementation 'org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.3'
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
}

kotlin {
    jvmToolchain(21)
}
